---
- name: Get tempest pod object
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: openstack
    label_selectors:
      - job-name=tempest-run-tests
  register: _tempest_pod_obj

- name: slurp Subunit file
  ansible.builtin.slurp:
    src: /tmp/stestr/results.subunit
  register: _tempest_results_subunit
  delegate_to: "{{ _tempest_pod_obj.resources[0].spec.nodeName }}"

- name: Save Subunit file
  ansible.builtin.copy:
    content: "{{ _tempest_results_subunit.content | b64decode }}"
    dest: "{{ tempest_subunit_path }}"
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  register: _tempest_subunit_copy

- name: Convert results from Subunit to JUNIT XML
  ansible.builtin.shell: "cat {{ tempest_subunit_path }} | subunit2junitxml -o {{ tempest_junit_path }}"
  register: subunitOutput
  failed_when: subunitOutput.rc >= 2 # this is here that the pipeline doesn't break before the actual job which then registers the whole tests to the main piepline
  when: _tempest_subunit_copy.changed
  delegate_to: localhost
