# List of annotations to apply to the Ingress
ingress_annotations: {}

ingress_class_name: "{{ atmosphere_ingress_class_name }}"

# ingress_name: string

# ingress_namespace: string

# ingress_host: string

# ingress_service_name: string

# ingress_service_port: number

# ingress_secret_name: string
